version: '3.9'
services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    command:
      '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./pkg/prometheus:/etc/prometheus
      - prom_data:/prometheus
    ports:
      - "9092:9090"

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prom_data:

