HttpServer:
  port: ':8082'
  timeout: '30s'
  shutdown_timeout: '30s'
  read_timeout: '15s'
  write_timeout: '60s'

Database:
  host: 'localhost'
  port: '5432'
  db_name: 'postgres'
  username: 'postgres'
  password: 'postgres'

Auth:
  JwtSecretKey: "AllYourBase"
  PasswordSecretKey: "dsadjflshfjghfdjkggfdj21321"
  TimeToLive: 15m

redis:
  address: 'localhost:6379'
  db: 2
  TimeToLive: 24h

Transport:
  User:
    Host: http://127.0.0.1:9235
    Timeout: 5s
  UserGrpc:
    Host: localhost:9090
    Port: ':9090'

DebugServer:
  host: 'localhost'
  port: '8083'